apiVersion: v1
kind: Namespace
metadata:
  name: ml-team
  labels:
    purpose: training
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-train
  labels:
    purpose: multi-node-training
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference-prod
  labels:
    purpose: production-inference
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference-team
  labels:
    purpose: small-ai-services
